In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [66]:
def sus(FitnV, Nsel):
    """
    随机通用采样算法
    FitnV: 个体适应度矩阵
    Nsel: 被选择个体的数目
    returns: 被选择个体的索引号
    """

    Nind, ans = FitnV.shape
    cumfit = np.cumsum(FitnV, axis = 0)
    pick = np.random.uniform()
    trials = cumfit[Nind - 1, ans - 1] / Nsel * (pick + np.arange(Nsel))
    trials = trials.reshape(ans, Nsel)
    Mf = cumfit @ np.ones(shape = (1, Nsel))
    # Mt = trials @ np.ones(shape = (1, Nind))
    print(Mf)
    # print(Mt)
    print(trials)
    
    return index


In [67]:
FitnV = np.array([[1], [3], [2], [9], [7], [5], [12], [11], [8], [4]])
Nsel = 6
index = sus(FitnV, Nsel)
print(index)

[[ 1.  1.  1.  1.  1.  1.]
 [ 4.  4.  4.  4.  4.  4.]
 [ 6.  6.  6.  6.  6.  6.]
 [15. 15. 15. 15. 15. 15.]
 [22. 22. 22. 22. 22. 22.]
 [27. 27. 27. 27. 27. 27.]
 [39. 39. 39. 39. 39. 39.]
 [50. 50. 50. 50. 50. 50.]
 [58. 58. 58. 58. 58. 58.]
 [62. 62. 62. 62. 62. 62.]]
[[ 7.08956599 17.42289932 27.75623265 38.08956599 48.42289932 58.75623265]]
[6. 7. 4. 6. 5. 6.]


In [3]:
help(np.argsort)

Help on function argsort in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stab