# 文本、文件操作

In [1]:
import numpy as np

In [2]:
#文本文件存取(savetxt(), loadtxt())

a = np.random.randint(1, 100, (4, 4))    #创建4*4整型数组
#将数组a存入txt文档
np.savetxt(fname='cgxf_a.txt', X=a, fmt='%d', delimiter=' & ', newline='\\\\\n\\hline\n')
#注：fmt  保存的数据类型    delimiter  分隔符    newline  分隔行

np.savetxt(fname='cgxf_a1.txt', X=a, fmt='%d')
b = np.loadtxt(fname='cgxf_a1.txt', dtype=int)
print(b)

[[69  4 72 35]
 [48 87 58 22]
 [58 33 87 13]
 [39 26 64  3]]


In [3]:
a = np.arange(25).reshape(5, 5)
np.savetxt(fname='cgxf_a2.txt', X=a, fmt='%d', delimiter=' ', newline='\n')
# np.savetxt('cgxf_a2.txt', a, '%d')
#打开cgxf_a2.txt，并构建数组
b = np.loadtxt(fname='cgxf_a2.txt')
c = b[0:2, 1:4].astype(int)    #astype()  转换类型为int
print(b, '\n\n', c)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]] 

 [[1 2 3]
 [6 7 8]]


In [4]:
#genfromtxt()读入文本文件
#几个重要参数
"""
fname: 指定数据文件名
dtype: 读入数据的数据类型，默认浮点型
comments: 指定注释符，默认#，遇到#，不读入
delimiter: 指定数据集的列分隔符
skip_header: 是否跳过数据集的首行，默认不跳过
skip_footer: 是否跳过数据集的脚注，默认不跳过
missing_value: 指定缺失标记，如果数据集包含该标记，则默认为缺失值
filling_value: 指定缺失值的填充
usecols: 指定需要读入的列
names: 为读入数据的列设置列名
endoding: 如果文件中含有中文，有时需要指定字符编码
"""

#读取前5行前5列数据
a = np.genfromtxt('cgxf_gft.txt', max_rows=5, usecols=range(5))
print(a, '\n')
#读取第6列数据
b = np.genfromtxt('cgxf_gft.txt', dtype=str, max_rows=5, usecols=[5])
print(b, '\n')
##删除kg，并转换成浮点类型
b1 = list()
for v in b:
    b1.append(float(v.rstrip('kg')))
b1 = np.array(b1)
print(b1, '\n')
#读入最后一行数据
c = np.genfromtxt(fname='cgxf_gft.txt', dtype=float, skip_footer=5, usecols=range(5))
print(c)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]] 

['60kg' '55kg' '51kg' '43kg' '41kg'] 

[60. 55. 51. 43. 41.] 

[0. 1. 2. 3. 4.]


In [4]:
#tofile, fromfile存取二进制格式文件
a = np.arange(8).reshape(2, 4)
#将数组a以二进制形式存入文件
a.tofile('cgxf_a001.bin')
#读取二进制文件
b = np.fromfile(file='cgxf_a001.bin', dtype=int).reshape(2, 4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [5]:
#Numpy专用的二进制文件存取函数
#load(), save(), savez()
a = np.random.randint(0, 100, 20).reshape(4, 5)
#存入文件
np.save('cgxf_a010.npy', a)
#打开文件
b = np.load('cgxf_a010.npy')
print(b)
c = np.sin(b)
np.savez('cgxf_a011.npz', b, c)
d = np.load('cgxf_a011.npz')
#用解压工具打开npz，会有两个文件(arr_0.npy, arr_1.npy)，即返回一个类似字典的对象
print(d['arr_0'])
print(d['arr_1'])

[[34 30 61  6  2]
 [53 68 30 60 94]
 [78 79 59 21 46]
 [ 6 37 24 25 35]]
[[34 30 61  6  2]
 [53 68 30 60 94]
 [78 79 59 21 46]
 [ 6 37 24 25 35]]
[[ 0.52908269 -0.98803162 -0.96611777 -0.2794155   0.90929743]
 [ 0.39592515 -0.89792768 -0.98803162 -0.30481062 -0.24525199]
 [ 0.51397846 -0.44411267  0.63673801  0.83665564  0.90178835]
 [-0.2794155  -0.64353813 -0.90557836 -0.13235175 -0.42818267]]


## 文件基本操作

In [6]:
#打开关闭文件
f = open('cgxf_a.txt', 'r')
print(f.name)
print(f.closed)
print(f.mode)
f.close

cgxf_a.txt
False
r


<function TextIOWrapper.close()>

In [7]:
f = open(file='cgxf_a.txt', mode='r')
s = f.read()
print(s)
# 统计文件中数字个数
n = 0
for i in s:
    if i in '1234567890':
        n += 1
print(n)

69 & 4 & 72 & 35\\
\hline
48 & 87 & 58 & 22\\
\hline
58 & 33 & 87 & 13\\
\hline
39 & 26 & 64 & 3\\
\hline

30


In [5]:
#向文本文件写入数据
fp = open(file='cgxf_w1.txt', mode='w')
str1 = ['hello', ' ', 'mathematic']
str2 = ['hello', 'mathematic']
fp.writelines(str1)
fp.write('\n')
fp.writelines(str2)
fp.close    #关闭文件
#读出数据
fp1 = open(file='cgxf_w1.txt', mode='r')
print(fp1.read())

hello mathematic
hellomathematic


In [7]:
#向cgxf_w1.txt文件追加
str3 = 'python is good'
fp = open(file='cgxf_w1.txt', mode='a')
fp.write('\n')
fp.writelines(str3)
fp.close

fp1 = open('cgxf_w1.txt', 'r')
print(fp1.read())

hello mathematic
hellomathematic
python is good
