## `numpy`，`numpy.linalg`解决线性代数问题

### 1. 向量和矩阵的运算

$ \alpha = [1, 2, 3]^T , \beta = [4, 5, 6]^T $ ，求 $ |\alpha|_2, \quad \alpha \cdot \beta, \quad \alpha \times \beta $

In [1]:
import numpy as np

# 创建数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a的范数为: ", np.linalg.norm(a))
print("a点乘b(a, b内积): ", np.dot(a, b))
print("a点乘b(a, b内积): ", np.inner(a, b))
print("a叉乘b(a, b外积): ", np.cross(a, b))

a的范数为:  3.7416573867739413
a点乘b(a, b内积):  32
a点乘b(a, b内积):  32
a叉乘b(a, b外积):  [-3  6 -3]


求 $ |A|, \quad rank(A), \quad A^T, \quad (A + 10E)^{-1}, \quad A^2, \quad AB $

In [2]:
import numpy as np

A = np.arange(1, 17).reshape(4, 4)      # 4阶矩阵
B = np.eye(4)                           # 4阶单位阵

print("|A|: ", np.linalg.det(A))
print("rank(A): ", np.linalg.matrix_rank(A))
print("A': \n", A.T, "\n", A.transpose())
print("A+10E的逆: \n", np.linalg.inv(A + 10 * B))
print("A^2: \n", np.dot(A, A))
print("AB: \n", np.dot(A, B))

|A|:  0.0
rank(A):  2
A': 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]] 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
A+10E的逆: 
 [[ 0.11277778  0.00333333 -0.00611111 -0.01555556]
 [-0.005       0.09       -0.015      -0.02      ]
 [-0.02277778 -0.02333333  0.07611111 -0.02444444]
 [-0.04055556 -0.03666667 -0.03277778  0.07111111]]
A^2: 
 [[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
AB: 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [3]:
import numpy as np
A = np.arange(1, 17).reshape(4, 4)      # 4阶矩阵
B = np.eye(4)                           # 4阶单位阵

print("横连矩阵: \n", np.c_[A, B])
print("纵连矩阵: \n", np.r_[A, B])

横连矩阵: 
 [[ 1.  2.  3.  4.  1.  0.  0.  0.]
 [ 5.  6.  7.  8.  0.  1.  0.  0.]
 [ 9. 10. 11. 12.  0.  0.  1.  0.]
 [13. 14. 15. 16.  0.  0.  0.  1.]]
纵连矩阵: 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
