# 数值计算工具NumPy

In [1]:
import numpy as np

使用help()函数查看函数用法

In [2]:
#数组的创建
a = np.array([1, 2, 3, 4, 5])
b = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9)))

print(a, '\n', b)

[1 2 3 4 5] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#指定数组类型
c = np.arange(0, 10, 2, dtype=int)
print(c)

[0 2 4 6 8]


In [4]:
#使用empty, linspace创建数组
d = np.empty((2, 3), dtype=int)    #创建2*3的整型空矩阵
e = np.linspace(1, 10, 5)
print(d, '\n', e)

[[204013088       568         0]
 [        0    131074         0]] 
 [ 1.    3.25  5.5   7.75 10.  ]


In [5]:
#整型随机数组
f = np.random.randint(2, 6, (3, 4))    #在[2, 6)间，随机生成3*4的整型数组
print(f)

[[5 3 2 5]
 [3 4 5 5]
 [2 2 3 3]]


In [6]:
#数组的属性
a = np.random.randint(0, 20, (4, 4))
print("维数：", a.ndim)
print("维度：", a.shape)
print("元素总数：", a.size)
print("类型：", a.dtype)
print('\n', a)

维数： 2
维度： (4, 4)
元素总数： 16
类型： int32

 [[ 6 14  4  9]
 [ 4  1  1 17]
 [ 9  9  7 19]
 [19  1  7 18]]


In [7]:
#数组元素索引
a = np.random.randint(10, 100, 8)
b = np.random.randint(10, 100, (5, 5))
print(a, '\n', b, '\n')
#一维数组索引
print(a[[2, 4, 6]])
print(a[[-1, -2, -3]])
#二维数组索引
print(b[1, 2], b[2, 3])    #输出第2行第3列，第3行第4列元素
print(b[3])    #输出第4行元素
print("第4行元素", b[3, :])
print("第3列元素", b[:, 2])

[47 58 11 21 46 30 17 47] 
 [[32 82 89 67 70]
 [60 67 27 70 32]
 [42 79 78 34 74]
 [96 92 25 33 59]
 [16 26 83 76 19]] 

[11 46 17]
[47 17 30]
27 34
[96 92 25 33 59]
第4行元素 [96 92 25 33 59]
第3列元素 [89 27 78 25 83]


In [8]:
#布尔索引
a = np.array([[1, np.nan, 2], [3, np.nan, 4]])
#取出非nan的数
b = a[~np.isnan(a)]
print(b)
#b中大于2的数
print(b[b>2])

[1. 2. 3. 4.]
[3. 4.]


In [9]:
#花式索引
x = np.random.randint(10, 100, (4, 5))
print(x, '\n\n')
#前两行元素
print(x[[0, 1]])
#前两列元素
print(x[:, [0, 1]])
#x[0][0], x[1][1]
print(x[[0, 1], [0, 1]])
#x[1][2], x[3][4]
print(x[[1, 3], [2, 4]])
#输出第1行，第2行，第1列，第2列组成的子矩阵
print(x[0:2, 0:2])

[[18 78 49 42 15]
 [40 75 14 19 36]
 [86 87 91 49 41]
 [90 89 28 40 19]] 


[[18 78 49 42 15]
 [40 75 14 19 36]]
[[18 78]
 [40 75]
 [86 87]
 [90 89]]
[18 75]
[14 19]
[[18 78]
 [40 75]]


In [10]:
#数组的修改
x = np.array([[1, 2, 3, 4], [5, 6, 7,8], [9, 10, 11, 12]])
print(x, '\n\n')
#修改x[1][1]为-1
x[1, 1] = -1
print(x, '\n')
#删除数组第3行(np.delete不对原数组进行修改)
y = np.delete(x, 2, axis=0)
print(y)
#删除数组第3列
z = np.delete(y, 2, axis=1)
print(z)
#增加一行(np.append不对原数组进行修改)
t1 = np.append(x, [[2, 4, 6, 8]], axis=0)
print(t1)
#增加一列
t2 = np.append(t1, [[1], [3], [5], [7]], axis=1)
print(t2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


[[ 1  2  3  4]
 [ 5 -1  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3  4]
 [ 5 -1  7  8]]
[[ 1  2  4]
 [ 5 -1  8]]
[[ 1  2  3  4]
 [ 5 -1  7  8]
 [ 9 10 11 12]
 [ 2  4  6  8]]
[[ 1  2  3  4  1]
 [ 5 -1  7  8  3]
 [ 9 10 11 12  5]
 [ 2  4  6  8  7]]


In [11]:
#使用reshape, resize对数组进行变形
a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
print(a, '\n', b, '\n')
print(a.reshape(4,), '\n', a, '\n')
print(a.resize(4,), '\n', a)

[[0 1]
 [2 3]] 
 [[0 1]
 [2 3]] 

[0 1 2 3] 
 [[0 1]
 [2 3]] 

None 
 [0 1 2 3]


In [12]:
#数组降维函数flatten, ravel
a = np.arange(9).reshape(3, 3)
b = np.arange(9).reshape(3, 3)
c = np.arange(9).reshape(3, 3)
#二维数组降成一维数组
print(a.reshape(-1), '\n', a)
print(b.flatten(), '\n', b)
print(c.ravel(), '\n', c)

[0 1 2 3 4 5 6 7 8] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#数组组合效果
a = np.arange(9).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
#垂直方向组合
c1 = np.vstack([a, b])
c2 = np.r_[a, b]
#水平方向组合
d1 = np.hstack([a, b])
d2 = np.c_[a, b]

print(c1, '\n\n', c2, '\n\n', d1, '\n\n', d2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

 [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]] 

 [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


In [14]:
#数组分割
a = np.random.randint(10, 100, 16).reshape(4, 4)
b = np.arange(4).reshape(2, 2)
#把a平均分成两个列数组
a1 = np.hsplit(a, 2)
#把b平均分成两个行数组
b1 = np.vsplit(b, 2)

print(a1[0], '\n', a1[1], '\n\n', a, '\n\n', b1[0], '\n', b1[1], '\n\n', b)

[[49 45]
 [38 71]
 [64 64]
 [67 86]] 
 [[48 67]
 [42 95]
 [24 38]
 [46 47]] 

 [[49 45 48 67]
 [38 71 42 95]
 [64 64 24 38]
 [67 86 46 47]] 

 [[0 1]] 
 [[2 3]] 

 [[0 1]
 [2 3]]


In [15]:
#numpy与math库的比较
import math, time
import numpy as np 

x = list(i * 0.01 for i in range(100000))

start = time.time()
y = list()
for i in x:
    y.append(math.sin(i))
end = time.time()
print('math.sin:', end-start)

start = time.time()
x1 = np.array(x)
y1 = np.sin(x1)
end = time.time()
print('np.sin:', end-start)

math.sin: 0.01994490623474121
np.sin: 0.004025459289550781
